spring:
  profiles:
    active:dev

---
server:
  port: 8001

# mybatis 配置
mybatis:
  type-aliases-package: com.it.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true # 开启二级缓存

# spring 的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-config-dept   #  3个服务名称一致
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  devtools:
    restart:
      enabled: true

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      # 注册中心地址7001-7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001   # 修改Eureka上的默认描述信息

# info配置
info:
  app.name: xiaohao-springcloud
  # 项目的名称
  company.name: 广西科技大学
  
---
server:
  port: 8001

# mybatis 配置
mybatis:
  type-aliases-package: com.it.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true # 开启二级缓存

# spring 的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-config-dept   #  3个服务名称一致
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  devtools:
    restart:
      enabled: true

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      # 注册中心地址7001-7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001   # 修改Eureka上的默认描述信息

# info配置
info:
  app.name: xiaohao-springcloud
  # 项目的名称
  company.name: 广西科技大学

